#pragma once
#include "CoreMinimal.h"
//CROSS-MODULE INCLUDE V2: -ModuleName=CoreUObject -ObjectName=Object -FallbackName=Object
#include "EEdGraphPinDirection.h"
#include "EdGraphPinType.h"
#include "EdGraphPin_Deprecated.generated.h"

class UEdGraphPin_Deprecated;

UCLASS(MinimalAPI)
class UEdGraphPin_Deprecated : public UObject {
    GENERATED_BODY()
public:
    UPROPERTY()
    FString PinName;
    
    UPROPERTY()
    FString PinToolTip;
    
    UPROPERTY()
    TEnumAsByte<EEdGraphPinDirection> Direction;
    
    UPROPERTY()
    FEdGraphPinType PinType;
    
    UPROPERTY()
    FString DefaultValue;
    
    UPROPERTY()
    FString AutogeneratedDefaultValue;
    
    UPROPERTY()
    UObject* DefaultObject;
    
    UPROPERTY()
    FText DefaultTextValue;
    
    UPROPERTY()
    TArray<UEdGraphPin_Deprecated*> LinkedTo;
    
    UPROPERTY()
    TArray<UEdGraphPin_Deprecated*> SubPins;
    
    UPROPERTY()
    UEdGraphPin_Deprecated* ParentPin;
    
    UPROPERTY()
    UEdGraphPin_Deprecated* ReferencePassThroughConnection;
    
    UEdGraphPin_Deprecated();
};

